# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tom's Profile
tagline:          ''
description:      ''
url:              https://tomp332.github.io
baseurl:          tomp332.github.io


github:
  repo:           https://github.com/tomp332/tomp332.github.io
